kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-data-pvc
spec:
  storageClassName: rabbitmq-data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi